"""Keywords and their determiners must be unique now.

Revision ID: b618d1f97535
Revises: 935a6477595e
Create Date: 2021-10-15 18:18:13.405974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b618d1f97535'
down_revision = '935a6477595e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'keywords', ['keyword', 'determiner'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'keywords', type_='unique')
    # ### end Alembic commands ###
